### ISSUE TITLE
Any easy example to execute the two method in this package in practical breeding program?

### ISSUE THREAD

**Issue by xiahui625649** [makoto-yamashita/OpSel.jl#3]
Maybe it's because of my poor understanding of mathematical formulas. I want to get started with this package quickly. Can you provide an example? Thanks in advance!

**Comment by makoto-yamashita** [comment]
Dear xiahui,  thanks for your interest in the package.
Test examples are also downloaded when the package is installed. The use of the test examples can be found at 
https://github.com/makoto-yamashita/OpSel.jl/blob/master/README.md
If you have your own data, Step 3 of Section "Usage" would be useful.

**Comment by xiahui625649** [comment]
> Dear xiahui, thanks for your interest in the package. Test examples are also downloaded when the package is installed. The use of the test examples can be found at https://github.com/makoto-yamashita/OpSel.jl/blob/master/README.md If you have your own data, Step 3 of Section "Usage" would be useful.

Thanks for your reply. I don't understand u mean what? For example, my trait is tree height, and its breeding value calculated by MLM is -0.12. How to calculate its upper limit value? Is it the sum of the mean and breeding value plus 1.96 times the standard deviation of the estimated breeding value?

**Comment by makoto-yamashita** [comment]
Thanks for your mail. The value "u" is an input data that users supply. 
For example, if u = 50 for the $i$th genotype and N=2800, x_i (the contribution of the $i$th genotype) is bounded by x_i <= 50/2800. Since the sum of the contributions is the unit, it holds that \sum_{i} x_i = 1.

The generation of the test data provided in this package is shortly described at
https://github.com/makoto-yamashita/OpSel.jl#data

**Comment by xiahui625649** [comment]
Thank you for your answer! How can I determine the U value for each genotype? Can the inbreeding coefficient come from the G matrix besides the A matrix? If my data is the measured data from the full-sib offspring of trees, including parental information and phenotypic traits, how can I quickly generate and prepare the input data? Thanks in advance.

**Comment by makoto-yamashita** [comment]
I am sorry that I am not familiar with data generation. Could you please check POPSIM and its manual?
https://www.skogforsk.se/popsim/
